services:
  guestbook:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - AIR_INSTALL_PATH=/usr/local/bin
    volumes:
      - .:/app
    depends_on:
      - redis
    # Définir explicitement la commande à exécuter pour éviter les problèmes d'entrypoint
    command: ["go", "run", "main.go"]
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: